#!/bin/sh
set -e

if [ "$1" = "configure" ] && command -v systemd-sysusers >/dev/null 2>&1; then
    systemd-sysusers /usr/lib/sysusers.d/wg-manager-controller.conf
fi

# debhelper inserts sysusers/systemd integration here.
#DEBHELPER#

if [ "$1" = "configure" ]; then
    install -d -o root -g root       -m 0755 /etc/wg-manager
    install -d -o root -g root       -m 0755 /etc/wg-manager/cert
    install -d -o root -g wg-manager -m 0750 /etc/wg-manager/cert/controller

    if [ -e /etc/wg-manager/wg-manager.conf ]; then
        chown root:wg-manager /etc/wg-manager/wg-manager.conf
        chmod 0640 /etc/wg-manager/wg-manager.conf
    fi

    if [ -e /etc/wg-manager/cert/ca.crt ]; then
        chown root:root /etc/wg-manager/cert/ca.crt
        chmod 0644 /etc/wg-manager/cert/ca.crt
    fi
    if [ -e /etc/wg-manager/cert/controller/server.crt ]; then
        chown root:wg-manager /etc/wg-manager/cert/controller/server.crt
        chmod 0644 /etc/wg-manager/cert/controller/server.crt
    fi
    if [ -e /etc/wg-manager/cert/controller/server.key ]; then
        chown root:wg-manager /etc/wg-manager/cert/controller/server.key
        chmod 0640 /etc/wg-manager/cert/controller/server.key
    fi
fi

exit 0
