#!/bin/sh
set -e

# debhelper inserts sysusers/systemd integration here.
#DEBHELPER#

if [ "$1" = "configure" ]; then
    install -d -o root -g root       -m 0755 /etc/wg-manager/cert
    install -d -o root -g wg-manager -m 0750 /etc/wg-manager/cert/controller

    if [ -e /etc/wg-manager/cert/ca.crt ]; then
        chown root:root /etc/wg-manager/cert/ca.crt
        chmod 0644 /etc/wg-manager/cert/ca.crt
    fi
    if [ -e /etc/wg-manager/cert/controller/server.crt ]; then
        chown root:wg-manager /etc/wg-manager/cert/controller/server.crt
        chmod 0644 /etc/wg-manager/cert/controller/server.crt
    fi
    if [ -e /etc/wg-manager/cert/controller/server.key ]; then
        chown root:wg-manager /etc/wg-manager/cert/controller/server.key
        chmod 0640 /etc/wg-manager/cert/controller/server.key
    fi
fi

exit 0
