[manager]
interface = wg0

[tls]
server_cert =/home/main/Desktop/wg_manager/cert/server.crt
server_key = /home/main/Desktop/wg_manager/cert/server.key
client_ca = /home/main/Desktop/wg_manager/cert/ca.crt

[policy]
vpn_network = 10.8.0.0/24
