#!/usr/bin/env python3
"""
publish_docs.py

Generate the public documentation for wg_manager and publish it to GitHub.

Pipeline:

    project source
        |
        +--> project_index.py
        |
        +--> protocol_flow.py src/wg_auth
        +--> protocol_flow.py src/wg_client
        +--> protocol_flow.py src/wg_manager
        |
        +--> docs/
                |
                +--> validation
                |
                +--> temporary git staging repository
                        |
                        +--> commit
                        +--> push
                        +--> GitHub Pages

The project itself does NOT need to be a Git repository.

Only the generated docs/ tree is published.
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

GITHUB_REPO = "manzosgorgo/wg-manager-docs"

PROTOCOLS = {
    "wg_auth": "src/wg_auth",
    "wg_client": "src/wg_client",
    "wg_manager": "src/wg_manager",
    "wg_all": "src",
}

PROTOCOL_OUTPUTS = {
    "wg_auth": "wg_auth_proto.md",
    "wg_client": "wg_client_proto.md",
    "wg_manager": "wg_manager_proto.md",
    "wg_all": "wg_all_proto.md",
}

PRIVATE_KEY_MARKERS = (
    "-----BEGIN PRIVATE KEY-----",
    "-----BEGIN RSA PRIVATE KEY-----",
    "-----BEGIN EC PRIVATE KEY-----",
    "-----BEGIN OPENSSH PRIVATE KEY-----",
)


# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

SCRIPT_PATH = Path(__file__).resolve()
PROJECT_ROOT = SCRIPT_PATH.parent.parent
TOOLS_DIR = PROJECT_ROOT / "tools"
DOCS_DIR = PROJECT_ROOT / "docs"
AI_DIR = DOCS_DIR / "ai"

PROJECT_INDEX = TOOLS_DIR / "project_index.py"
PROTOCOL_FLOW = TOOLS_DIR / "protocol_flow.py"


# ---------------------------------------------------------------------------
# Utility functions
# ---------------------------------------------------------------------------

def run(
    command: list[str],
    *,
    cwd: Path | None = None,
    capture: bool = False,
) -> subprocess.CompletedProcess[str]:
    """Run a command and fail loudly on errors."""

    print("$", " ".join(command))

    return subprocess.run(
        command,
        cwd=cwd,
        check=True,
        text=True,
        capture_output=capture,
    )


def command_exists(command: str) -> bool:
    return shutil.which(command) is not None


def fail(message: str) -> "NoReturn":
    print(f"\nERROR: {message}", file=sys.stderr)
    raise SystemExit(1)


# ---------------------------------------------------------------------------
# Documentation generation
# ---------------------------------------------------------------------------

def clean_obsolete_generated_site() -> None:
    """
    Remove the old HTML site generated by build_docs.py.

    We deliberately do not recursively delete arbitrary HTML files because
    source HTML files may legitimately be part of the project documentation.
    """

    old_site = DOCS_DIR / "site"

    if old_site.exists():
        print(f"Removing obsolete generated site: {old_site}")
        shutil.rmtree(old_site)

    # Old generated landing page. The public documentation is now Markdown.
    old_index = DOCS_DIR / "index.html"

    if old_index.exists():
        print(f"Removing obsolete generated index: {old_index}")
        old_index.unlink()


def generate_project_index() -> None:
    print("\n[1/6] Generating project index")

    if not PROJECT_INDEX.is_file():
        fail(f"project_index.py not found: {PROJECT_INDEX}")

    run(
        [
            sys.executable,
            str(PROJECT_INDEX),
            str(PROJECT_ROOT),
            "--output",
            str(AI_DIR),
            "--clean",
        ],
        cwd=PROJECT_ROOT,
    )


def generate_protocol(name: str, source_relative: str) -> None:
    """
    Run protocol_flow.py with the component directory itself as the repo root.

    protocol_flow.py writes its Markdown report to stdout, so stdout becomes
    the generated protocol snapshot.
    """

    print(f"\nGenerating protocol snapshot: {name}")

    source_root = PROJECT_ROOT / source_relative
    output_name = PROTOCOL_OUTPUTS[name]
    output_path = AI_DIR / output_name

    if not source_root.is_dir():
        fail(f"Protocol source directory does not exist: {source_root}")

    result = run(
        [
            sys.executable,
            str(PROTOCOL_FLOW),
            str(source_root),
            "--no-tests",
        ],
        cwd=PROJECT_ROOT,
        capture=True,
    )

    output = result.stdout

    if not output.strip():
        fail(
            f"protocol_flow.py produced empty output for {name}: "
            f"{source_root}"
        )

    output_path.write_text(output, encoding="utf-8")

    print(f"  -> {output_path}")


def generate_protocol_snapshots() -> None:
    print("\n[2/6] Generating protocol snapshots")

    if not PROTOCOL_FLOW.is_file():
        fail(f"protocol_flow.py not found: {PROTOCOL_FLOW}")

    AI_DIR.mkdir(parents=True, exist_ok=True)

    for name, source_relative in PROTOCOLS.items():
        generate_protocol(name, source_relative)


def generate_readme() -> None:
    """
    Generate docs/README.md.

    This becomes README.md at the root of the public GitHub repository.
    """

    print("\n[3/6] Generating documentation README")

    readme = """# wg-manager documentation

Automatically generated documentation for the `wg_manager` project.

> This repository contains generated documentation and analysis artifacts.
> It is observational documentation of the current project tree, not a
> normative architecture specification.

## Project analysis

- [AI index](ai/README.md)
- [Project tree](ai/TREE.md)
- [Modules](ai/MODULES.md)
- [Dependencies](ai/DEPENDENCIES.md)
- [Symbols](ai/SYMBOLS.md)
- [Connections](ai/CONNECTIONS.md)

## Protocol snapshots

- [wg-auth protocol](ai/wg_auth_proto.md)
- [wg-client protocol](ai/wg_client_proto.md)
- [wg-manager protocol](ai/wg_manager_proto.md)
- [wg-all protocol](ai/wg_all_proto.md)

## Source documentation

The [`ai/files/`](ai/files/) directory contains generated documentation
for the individual source files discovered by the project indexer.

## Generation

The documentation is generated mechanically from the `wg_manager` source
tree using the analysis tools in the project.

The protocol snapshots are generated independently for:

- `src/wg_auth`
- `src/wg_client`
- `src/wg_manager`
"""

    DOCS_DIR.mkdir(parents=True, exist_ok=True)

    (DOCS_DIR / "README.md").write_text(
        readme,
        encoding="utf-8",
    )
    config="""

    """
    (DOCS_DIR / "_config.yml").write_text(
        config,
        encoding="utf-8",
    )

# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------

def validate_required_files() -> None:
    print("\n[4/6] Validating generated documentation")

    required = [
        DOCS_DIR / "README.md",
        AI_DIR / "README.md",
        AI_DIR / "TREE.md",
        AI_DIR / "MODULES.md",
        AI_DIR / "DEPENDENCIES.md",
        AI_DIR / "SYMBOLS.md",
        AI_DIR / "CONNECTIONS.md",
        AI_DIR / "wg_auth_proto.md",
        AI_DIR / "wg_client_proto.md",
        AI_DIR / "wg_manager_proto.md",
        AI_DIR / "wg_all_proto.md",
    ]

    missing = [path for path in required if not path.is_file()]

    if missing:
        for path in missing:
            print(f"  missing: {path}", file=sys.stderr)

        fail("documentation validation failed")


def validate_no_private_keys() -> None:
    """
    Second safety barrier against accidentally publishing key material.

    project_index.py already excludes sensitive source files. This scan is
    intentionally independent of that mechanism.
    """

    suspicious = []

    for path in DOCS_DIR.rglob("*"):
        if not path.is_file():
            continue

        # Ignore binary-looking files.
        try:
            data = path.read_bytes()
        except OSError:
            continue

        for marker in PRIVATE_KEY_MARKERS:
            if marker.encode("utf-8") in data:
                suspicious.append((path, marker))

    if suspicious:
        print(
            "\nPossible private key material found:",
            file=sys.stderr,
        )

        for path, marker in suspicious:
            print(f"  {path}: {marker}", file=sys.stderr)

        fail("refusing to publish possible private key material")


def validate_no_obsolete_site() -> None:
    old_site = DOCS_DIR / "site"

    if old_site.exists():
        fail(f"obsolete HTML site still exists: {old_site}")


def validate_docs() -> None:
    validate_required_files()
    validate_no_private_keys()
    validate_no_obsolete_site()

    print("Documentation validation: OK")


# ---------------------------------------------------------------------------
# GitHub repository
# ---------------------------------------------------------------------------

def github_repo_exists() -> bool:
    result = subprocess.run(
        [
            "gh",
            "repo",
            "view",
            GITHUB_REPO,
        ],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )

    return result.returncode == 0


def ensure_github_repo() -> None:
    print("\nChecking GitHub repository")

    if github_repo_exists():
        print(f"GitHub repository exists: {GITHUB_REPO}")
        return

    print(f"Creating public GitHub repository: {GITHUB_REPO}")

    run(
        [
            "gh",
            "repo",
            "create",
            GITHUB_REPO,
            "--public",
        ],
        cwd=PROJECT_ROOT,
    )


def get_default_branch() -> str:
    result = run(
        [
            "gh",
            "repo",
            "view",
            GITHUB_REPO,
            "--json",
            "defaultBranchRef",
            "--jq",
            ".defaultBranchRef.name",
        ],
        cwd=PROJECT_ROOT,
        capture=True,
    )

    branch = result.stdout.strip()

    # An empty repository may not have a default branch yet.
    return branch or "main"


# ---------------------------------------------------------------------------
# Staging
# ---------------------------------------------------------------------------

def copy_docs_to_staging(staging: Path) -> None:
    """
    Make staging contain exactly the contents of docs/.
    """

    for item in staging.iterdir():
        if item.name == ".git":
            continue

        if item.is_dir():
            shutil.rmtree(item)
        else:
            item.unlink()

    for item in DOCS_DIR.iterdir():
        destination = staging / item.name

        if item.is_dir():
            shutil.copytree(item, destination)
        else:
            shutil.copy2(item, destination)


def prepare_staging(staging: Path, branch: str) -> None:
    """
    Prepare a complete Git repository in the temporary staging directory.

    If the remote already has history, clone it.

    If the remote repository is empty, initialize it locally.
    """

    remote = f"https://github.com/{GITHUB_REPO}.git"

    # Try cloning first. This handles normal existing repositories.
    clone_result = subprocess.run(
        [
            "git",
            "clone",
            remote,
            str(staging),
        ],
        cwd=PROJECT_ROOT,
        text=True,
        capture_output=True,
    )

    if clone_result.returncode != 0:
        # Empty repositories cannot always be cloned depending on their
        # current GitHub state. Initialize a fresh repository instead.
        print("Remote repository has no usable history; initializing staging.")

        run(
            [
                "git",
                "init",
                "-b",
                branch,
            ],
            cwd=staging,
        )

        run(
            [
                "git",
                "remote",
                "add",
                "origin",
                remote,
            ],
            cwd=staging,
        )
    else:
        # The clone created the directory and its .git.
        pass


def configure_git_identity(staging: Path) -> None:
    """
    Configure a local identity only if Git does not already have one.

    We use GitHub's noreply identity so the publisher does not depend on
    the user's global Git configuration.
    """

    email = subprocess.run(
        ["git", "config", "--get", "user.email"],
        cwd=staging,
        text=True,
        capture_output=True,
    )

    name = subprocess.run(
        ["git", "config", "--get", "user.name"],
        cwd=staging,
        text=True,
        capture_output=True,
    )

    if not email.stdout.strip():
        run(
            [
                "git",
                "config",
                "user.email",
                "41898282+github-actions[bot]@users.noreply.github.com",
            ],
            cwd=staging,
        )

    if not name.stdout.strip():
        run(
            [
                "git",
                "config",
                "user.name",
                "wg-manager documentation publisher",
            ],
            cwd=staging,
        )


def stage_docs(staging: Path) -> None:
    copy_docs_to_staging(staging)

    run(
        [
            "git",
            "add",
            "--all",
        ],
        cwd=staging,
    )


def has_staged_changes(staging: Path) -> bool:
    result = subprocess.run(
        [
            "git",
            "diff",
            "--cached",
            "--quiet",
        ],
        cwd=staging,
    )

    return result.returncode != 0


def commit_and_push(staging: Path, branch: str) -> bool:
    """
    Commit and push.

    Returns True when something was pushed, False when documentation was
    already up to date.
    """

    if not has_staged_changes(staging):
        print("\nDocumentation unchanged; nothing to commit or push.")
        return False

    run(
        [
            "git",
            "commit",
            "-m",
            "Update generated documentation",
        ],
        cwd=staging,
    )

    # For an initialized empty repository, establish the branch.
    run(
        [
            "git",
            "branch",
            "-M",
            branch,
        ],
        cwd=staging,
    )

    run(
        [
            "git",
            "push",
            "--set-upstream",
            "origin",
            branch,
        ],
        cwd=staging,
    )

    return True


# ---------------------------------------------------------------------------
# GitHub Pages
# ---------------------------------------------------------------------------

def configure_pages(branch: str) -> None:
    """
    Configure GitHub Pages to publish the root of the default branch.

    The repository itself remains Markdown-first. GitHub Pages/Jekyll can
    render the Markdown files as a web site.
    """

    print("\nConfiguring GitHub Pages")

    # First inspect current Pages configuration.
    result = subprocess.run(
        [
            "gh",
            "api",
            f"/repos/{GITHUB_REPO}/pages",
        ],
        cwd=PROJECT_ROOT,
        text=True,
        capture_output=True,
    )

    if result.returncode == 0:
        print("GitHub Pages already configured.")

        # Try to update it to the desired source.
        update = subprocess.run(
            [
                "gh",
                "api",
                "--method",
                "PUT",
                f"/repos/{GITHUB_REPO}/pages",
                "-f",
                f"source[branch]={branch}",
                "-f",
                "source[path]=/",
            ],
            cwd=PROJECT_ROOT,
            text=True,
            capture_output=True,
        )

        if update.returncode == 0:
            print(f"GitHub Pages source: {branch}:/")
        else:
            print(
                "Warning: existing Pages configuration could not be updated.",
                file=sys.stderr,
            )

        return

    # Pages is not configured yet.
    create = subprocess.run(
        [
            "gh",
            "api",
            "--method",
            "POST",
            f"/repos/{GITHUB_REPO}/pages",
            "-f",
            f"source[branch]={branch}",
            "-f",
            "source[path]=/",
        ],
        cwd=PROJECT_ROOT,
        text=True,
        capture_output=True,
    )

    if create.returncode != 0:
        print(
            "Warning: GitHub Pages could not be configured automatically.",
            file=sys.stderr,
        )
        print(create.stderr, file=sys.stderr)
        return

    print(f"GitHub Pages configured from {branch}:/")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate and publish wg_manager documentation."
    )

    parser.add_argument(
        "--repo",
        default=GITHUB_REPO,
        help=f"GitHub repository (default: {GITHUB_REPO})",
    )

    parser.add_argument(
        "--no-push",
        action="store_true",
        help="Generate and validate documentation but do not push.",
    )

    parser.add_argument(
        "--no-pages",
        action="store_true",
        help="Do not configure GitHub Pages.",
    )

    return parser.parse_args()


def main() -> int:
    global GITHUB_REPO

    args = parse_args()
    GITHUB_REPO = args.repo

    print("=" * 72)
    print("wg-manager documentation publisher")
    print("=" * 72)
    print(f"Project : {PROJECT_ROOT}")
    print(f"Docs    : {DOCS_DIR}")
    print(f"GitHub  : {GITHUB_REPO}")

    if not command_exists("git"):
        fail("git command not found")

    if not command_exists("gh"):
        fail("gh command not found")

    if not PROJECT_ROOT.is_dir():
        fail(f"project root does not exist: {PROJECT_ROOT}")

    if not TOOLS_DIR.is_dir():
        fail(f"tools directory does not exist: {TOOLS_DIR}")

    DOCS_DIR.mkdir(parents=True, exist_ok=True)

    # ------------------------------------------------------------------
    # Generate
    # ------------------------------------------------------------------

    clean_obsolete_generated_site()

    generate_project_index()
    generate_protocol_snapshots()
    generate_readme()

    # ------------------------------------------------------------------
    # Validate
    # ------------------------------------------------------------------

    validate_docs()

    if args.no_push:
        print("\n--no-push specified; stopping after documentation generation.")
        return 0

    # ------------------------------------------------------------------
    # GitHub
    # ------------------------------------------------------------------

    ensure_github_repo()

    branch = get_default_branch()

    print(f"\nUsing GitHub default branch: {branch}")

    # ------------------------------------------------------------------
    # Temporary staging repository
    # ------------------------------------------------------------------

    print("\n[5/6] Preparing temporary Git staging area")

    with tempfile.TemporaryDirectory(
        prefix="wg-manager-docs-publish-"
    ) as temp_dir:

        staging = Path(temp_dir) / "repo"

        prepare_staging(staging, branch)
        configure_git_identity(staging)

        stage_docs(staging)

        pushed = commit_and_push(staging, branch)

    # ------------------------------------------------------------------
    # Pages
    # ------------------------------------------------------------------

    if not args.no_pages:
        configure_pages(branch)

    print("\n[6/6] Publication complete")

    if pushed:
        print(f"Published: https://github.com/{GITHUB_REPO}")
    else:
        print("Remote documentation was already up to date.")

    if not args.no_pages:
        print(
            "Pages:",
            f"https://{GITHUB_REPO.split('/')[0]}.github.io/"
            f"{GITHUB_REPO.split('/')[1]}/",
        )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
